name: Publish PyPi and GitHub Release
run-name: ${{ github.actor }} is sending new release to PyPi 🚀
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build standard package
        run: |
          python -m build

      - name: Check package metadata
        run: |
          twine check dist/*

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
